"""empty message

Revision ID: 1fc618fac5f5
Revises: 
Create Date: 2024-03-15 12:57:44.995405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc618fac5f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('propertyId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('location', sa.String(length=280), nullable=False),
    sa.Column('no_of_bedrooms', sa.Integer(), nullable=False),
    sa.Column('no_of_bathrooms', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('property_type', sa.String(length=15), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('photo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('propertyId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
